# Generated by Django 5.2.8 on 2025-11-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='placa',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_placa',
            field=models.CharField(default='SIN_PLACA', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('', '---------'), ('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Negro', 'Negro'), ('Blanco', 'Blanco')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='SIN_MARCA', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(default='SIN_MODELO', max_length=30),
        ),
    ]
