# Generated by Django 5.2.8 on 2025-11-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosapp', '0002_remove_vehiculo_placa_vehiculo_numero_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('', '---------'), ('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Negro', 'Negro'), ('Blanco', 'Blanco')], default='', max_length=10),
        ),
    ]
