# Generated by Django 5.2.8 on 2025-11-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosapp', '0004_vehicle_delete_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_placa', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
